{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "return-service.fullname" . }}-network-policy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "return-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "return-service.selectorLabels" . | nindent 6 }}
      service: {{ .Values.name }}
  policyTypes:
    - Ingress
    - Egress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

