apiVersion: v2
name: monitoring
description: A Helm chart for Monitoring Stack - Prometheus, Grafana, and Alertmanager
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - monitoring
  - prometheus
  - grafana
  - alertmanager
  - metrics
maintainers:
  - name: DevOps Team
dependencies:
  - name: prometheus
    version: 25.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 7.0.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: alertmanager
    version: 1.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: alertmanager.enabled

