apiVersion: v2
name: order-service
description: A Helm chart for Order Service - Order management service for ecommerce platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - order
  - ecommerce
  - microservices
  - ecommerce
maintainers:
  - name: DevOps Team
home: https://github.com/yourorg/ecommerce
sources:
  - https://github.com/yourorg/ecommerce

