apiVersion: v2
name: gateway-service
description: A Helm chart for Gateway Service - API Gateway for ecommerce platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - gateway
  - api-gateway
  - microservices
  - ecommerce
maintainers:
  - name: DevOps Team
home: https://github.com/yourorg/ecommerce
sources:
  - https://github.com/yourorg/ecommerce

