apiVersion: v2
name: auth-service
description: A Helm chart for Auth Service - Authentication and authorization service for ecommerce platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - auth
  - authentication
  - authorization
  - microservices
  - ecommerce
maintainers:
  - name: DevOps Team
home: https://github.com/yourorg/ecommerce
sources:
  - https://github.com/yourorg/ecommerce

