{{- if .Values.priorityClasses.enabled }}
{{- if .Values.priorityClasses.critical.enabled }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClasses.critical.name }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
value: {{ .Values.priorityClasses.critical.value }}
globalDefault: {{ .Values.priorityClasses.critical.globalDefault }}
description: {{ .Values.priorityClasses.critical.description }}
preemptionPolicy: {{ .Values.priorityClasses.critical.preemptionPolicy }}
{{- end }}

{{- if .Values.priorityClasses.high.enabled }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClasses.high.name }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
value: {{ .Values.priorityClasses.high.value }}
globalDefault: {{ .Values.priorityClasses.high.globalDefault }}
description: {{ .Values.priorityClasses.high.description }}
preemptionPolicy: {{ .Values.priorityClasses.high.preemptionPolicy }}
{{- end }}

{{- if .Values.priorityClasses.medium.enabled }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClasses.medium.name }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
value: {{ .Values.priorityClasses.medium.value }}
globalDefault: {{ .Values.priorityClasses.medium.globalDefault }}
description: {{ .Values.priorityClasses.medium.description }}
preemptionPolicy: {{ .Values.priorityClasses.medium.preemptionPolicy }}
{{- end }}
{{- end }}

