apiVersion: v2
name: logging
description: A Helm chart for Logging Stack - Loki and Promtail
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - logging
  - loki
  - promtail
  - logs
maintainers:
  - name: DevOps Team
dependencies:
  - name: loki
    version: 6.0.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: promtail
    version: 6.0.0
    repository: https://grafana.github.io/helm-charts
    condition: promtail.enabled

